### ISSUE TITLE
Release action

### ISSUE THREAD

**Issue by quinton22** [quinton22/VandyScheduler#12]
Create a github release action

**Comment by DavidHuang2002** [comment]
Hi Quinton I will look into how to do it. Should have some preliminary results by EOW. Might need you to provide the credentials for the Chrome store later.

**Comment by DavidHuang2002** [comment]
https://github.com/marketplace/actions/publish-chrome-extension-to-chrome-web-store

Seem pretty straightforward with this out-of-the-box solution. @quinton22, when you are free can you try following the instructions on there to set it up since you have access to the Chrome extension's developer console.
