### ISSUE TITLE
RateMyProfessor enhancements

### ISSUE THREAD

**Issue by quinton22** [quinton22/VandyScheduler#9]
- show the number of ratings along side rateMyProf scores.
- make the professor's name a link that goes directly to the rmp page

**Comment by DavidHuang2002** [comment]
Hi Quinton for the second feature -- "make the professor's name a link that goes directly to the rmp page" -- I have already added that functionality before.
For the first one "show the number of ratings alongside rateMyProf scores" - I have considered it before but I think that feature would be tricky to develop, add quite some overhead, and would hardly be necessary since everyone can just click into the link to verify the number of ratings (but that's just my personal opinion this is more of a judgment call). I will close it for now and if that feature becomes obviously necessary, we can re-open it.
